backend:
  name: github
  repo: yourusername/your-repo  # Change this to your repository
  branch: main                  # Use 'main' or the correct branch

media_folder: "images/uploads"   # Folder for uploaded images
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
